### ISSUE TITLE
SSLError issue when have a test in lab chart (local jupyter)

### ISSUE THREAD

**Issue by Kelukin** [odpi/egeria-jupyter-notebooks#3]
When I deployed a lab chart and ran common/environment-check.ipynb in the Jupyter, I triggered the following Exceptions:

```
Checking OMAG Server Platform availability...
Exception: HTTPSConnectionPool(host='lab-core', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
    Core Platform is down - start it before proceeding
Exception: HTTPSConnectionPool(host='lab-datalake', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
    Data Lake Platform is down - start it before proceeding
Exception: HTTPSConnectionPool(host='lab-dev', port=9443): Max retries exceeded with url: /open-metadata/platform-services/users/garygeeke/server-platform/origin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
    Dev Platform is down - start it before proceeding
Done.
```

I am unsure whether the cause is the unalignment between the Jupyter and Egeria's version since you specify the Jupyter tag to the latest and have just upgraded Jupyter to 3.10-SNAPSHOT.

**Comment by planetf1** [comment]
As part of the refactoring I plan to no longer build a special container, but rather use the standard Jupyter containers, which will retrieve our notebooks via an init script (supported by Jupyter container) or if that fails, a k8s init container. 

once that is done will address any issues with ssl certs - leaving open until then

**Comment by planetf1** [comment]
The refactoring is mostly done. Unfortunately I wasn't able to get the certificates sorted in the time available - in part because we need to create certs at deployment time .

Nor was it easy to control the behaviour within the environment, in part due to changes in the requests module and python. There's a capability to create a session - and manage context that way which was appealing, but also too much refactoring for now.

Therefore the first pass (along with moving the code) has disabled cert checking directly in calls to the requests module

As such I think this issue is now addressed.
